{{- range $name, $deployment := .Values.deployments }}
{{- if and $deployment.enabled (hasKey $deployment "autoscaling") $deployment.autoscaling (hasKey $deployment.autoscaling "enabled") $deployment.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  {{- $hpaName := "" }}
  {{- if $deployment.autoscaling.name }}
    {{- $hpaName = printf "%s-%s" $.Release.Name $deployment.autoscaling.name }}
  {{- else }}
    {{- $hpaName = include "app.hpaName" (list $ $name) }}
  {{- end }}
  name: {{ $hpaName }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    {{- $deploymentName := "" }}
    {{- if $deployment.name }}
      {{- $deploymentName = printf "%s-%s" $.Release.Name $deployment.name }}
    {{- else }}
      {{- $deploymentName = include "app.deploymentName" (list $ $name) }}
    {{- end }}
    name: {{ $deploymentName }}
  minReplicas: {{ $deployment.autoscaling.minReplicas | default 1 }}
  maxReplicas: {{ $deployment.autoscaling.maxReplicas | default 10 }}
  metrics:
    {{- if $deployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $deployment.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $deployment.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $deployment.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}