{{- /* Common Secret */}}
{{- if and .Values.common .Values.common.secret .Values.common.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "daa.secretName" (list . (.Values.common.secret.name | default "common")) }}
  labels:
    {{- include "daa.labels" . | nindent 4 }}
    {{- with .Values.common.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annotations := dict }}
  {{- if .Values.global.annotations }}
  {{- $annotations = merge $annotations .Values.global.annotations }}
  {{- end }}
  {{- if .Values.common.secret.annotations }}
  {{- $annotations = merge $annotations .Values.common.secret.annotations }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
type: {{ .Values.common.secret.type | default "Opaque" }}
{{- if .Values.common.secret.data }}
data:
  {{- toYaml .Values.common.secret.data | nindent 2 }}
{{- end }}
{{- if .Values.common.secret.stringData }}
stringData:
  {{- toYaml .Values.common.secret.stringData | nindent 2 }}
{{- end }}
{{- end }}

{{- /* Per-deployment Secrets */}}
{{- range $deploymentKey, $deployment := .Values.deployments }}
{{- if and $deployment.enabled $deployment.secret $deployment.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $deployment.secret.name | default (include "daa.secretName" (list $ $deploymentKey)) }}
  labels:
    {{- include "daa.resourceLabels" (list $ $deploymentKey) | nindent 4 }}
    {{- with $deployment.secret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annotations := dict }}
  {{- if $.Values.global.annotations }}
  {{- $annotations = merge $annotations $.Values.global.annotations }}
  {{- end }}
  {{- if $deployment.secret.annotations }}
  {{- $annotations = merge $annotations $deployment.secret.annotations }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
type: {{ $deployment.secret.type | default "Opaque" }}
{{- if $deployment.secret.data }}
data:
  {{- toYaml $deployment.secret.data | nindent 2 }}
{{- end }}
{{- if $deployment.secret.stringData }}
stringData:
  {{- toYaml $deployment.secret.stringData | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
